### ISSUE TITLE
Revmgo can't connect the secondary

### ISSUE THREAD

**Issue by admirestator** [jgraham909/revmgo#17]
Hi, I use revel and mgo with revmgo to build a restful service.I think you did a good job!
It works fine for a single mongod instance, but when I connected my app to a replica set, the app can only read from the primary node.Here is what I had tried.

+  <code>revmgo.dial = mongodb://172.0.15.22:27017, 172.20.135.23:27017, 172.20.135.24:27017</code>
+  Using <code>c.MongoSession.SetMode(mgo.Eventual, true)"</code>to change mode in my controller
+  Visit api with ab2 tools,
+ Watch mongod in a primary node and a secondary node with **mongotop**,

then I can only see the operation in primary node,and none in the secondary.

I also tried to example in https://labix.org/mgo. It works well, and I can see operation in both primary and secondary node.And then I use pure mgo in revel, it goes the situation like revmgo.

Could you give me a hand with this issue?
:-)

**Comment by jgraham909** [comment]
Have you tried without the spaces in your revmgo.dial declaration?

Also have you tried a debug like fmt.Println() just before revmgo's Dial call to see what value it is getting set to via `Dial = revel.Config.StringDefault("revmgo.dial", "localhost")`?

**Comment by admirestator** [comment]
I just tried what you had said, and it worked like the situation with spces. The Dial return the whole value of **revmgo.dial** in app.conf.

I also debuged the **SetMode()** method, right after the <code>Session, err = mgo.Dial(Dial)</code>
the <code>Session.Mode()</code> return 0 which is the value of  **mgo.Eventual**.And in the controller <code>c.MongoSession.Mode()</code> return the same value.

There must be something strange.

**Comment by jgraham909** [comment]
Please see updated Readme and #18
