### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by janekolszak** [jgraham909/revmgo#18]
revmgo seems to be a good idea but it also seems abandoned. Is anybody maintaining the code?

**Comment by jgraham909** [comment]
I have lost interest in revel, feel free to fork or join forces with others via the fork tree; https://github.com/jgraham909/revmgo/network

If any of the other forks is a front-runner I will happily update the README to redirect folks there.

**Comment by janekolszak** [comment]
I asked the on the other: creativelikeadog/revel-mgo but it also seems abandoned.
I forked your project into https://github.com/janekolszak/revmgo

I'll maintain it as long as possible, so you may add a remark about it in the README.

**Comment by jgraham909** [comment]
Updated the Readme to point to your repo. GL!
